import Head from "next/head";


import { useState, useEffect } from "react";

//mui components
import {
	Box,
	Typography,
	Grid,
	Select,
	FormControl,
	FormHelperText,
	InputLabel,
	Menu,
	MenuItem,
} from "@mui/material";

export default function InvoicePage() {
	useEffect(() => {
		let invoices = [];
		fetch("http://localhost:3000/api/hello")
			.then((res) => res.json())
			.then((data) => console.log(data));
	}, []);

	return (
		<>
			<Head>
				
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Box>user</Box>
		</>
	);
}
